/** Declaration file generated by dts-gen */


declare module 'timespan' {
    export class TimeSpan {
        constructor(milliseconds: any, seconds: any, minutes: any, hours: any, days: any);

        add(timeSpan: any): void;

        addDays(days: any): void;

        addHours(hours: any): void;

        addMilliseconds(milliseconds: any): void;

        addMinutes(minutes: any): void;

        addSeconds(seconds: any): void;

        equals(timeSpan: any): any;

        subtract(timeSpan: any): void;

        subtractDays(days: any): void;

        subtractHours(hours: any): void;

        subtractMilliseconds(milliseconds: any): void;

        subtractMinutes(minutes: any): void;

        subtractSeconds(seconds: any): void;

        toString(): any;

        totalDays(roundDown: any): any;

        totalHours(roundDown: any): any;

        totalMilliseconds(roundDown: any): any;

        totalMinutes(roundDown: any): any;

        totalSeconds(roundDown: any): any;

    }

    export function clone(timeSpan: any): any;

    export function fromDates(start: any, end: any, abs: any): any;

    export function fromDays(days: any): any;

    export function fromHours(hours: any): any;

    export function fromMilliseconds(milliseconds: any): any;

    export function fromMinutes(minutes: any): any;

    export function fromSeconds(seconds: any): any;

    export function instanceOf(timeSpan: any): any;

    export function parse(str: any): any;

    export function parseDate(str: any): any;

    export function test(str: any): any;

    export namespace TimeSpan {

        const days: number;

        const hours: number;

        const milliseconds: number;

        const minutes: number;

        const seconds: number;

        function add(timeSpan: any): void;

        function addDays(days: any): void;

        function addHours(hours: any): void;

        function addMilliseconds(milliseconds: any): void;

        function addMinutes(minutes: any): void;

        function addSeconds(seconds: any): void;

        function equals(timeSpan: any): any;

        function subtract(timeSpan: any): void;

        function subtractDays(days: any): void;

        function subtractHours(hours: any): void;

        function subtractMilliseconds(milliseconds: any): void;

        function subtractMinutes(minutes: any): void;

        function subtractSeconds(seconds: any): void;

        function toString(): any;

        function totalDays(roundDown: any): any;

        function totalHours(roundDown: any): any;

        function totalMilliseconds(roundDown: any): any;

        function totalMinutes(roundDown: any): any;

        function totalSeconds(roundDown: any): any;

        namespace add {
            const prototype: {
            };

        }

        namespace addDays {
            const prototype: {
            };

        }

        namespace addHours {
            const prototype: {
            };

        }

        namespace addMilliseconds {
            const prototype: {
            };

        }

        namespace addMinutes {
            const prototype: {
            };

        }

        namespace addSeconds {
            const prototype: {
            };

        }

        namespace equals {
            const prototype: {
            };

        }

        namespace subtract {
            const prototype: {
            };

        }

        namespace subtractDays {
            const prototype: {
            };

        }

        namespace subtractHours {
            const prototype: {
            };

        }

        namespace subtractMilliseconds {
            const prototype: {
            };

        }

        namespace subtractMinutes {
            const prototype: {
            };

        }

        namespace subtractSeconds {
            const prototype: {
            };

        }

        namespace toString {
            const prototype: {
            };

        }

        namespace totalDays {
            const prototype: {
            };

        }

        namespace totalHours {
            const prototype: {
            };

        }

        namespace totalMilliseconds {
            const prototype: {
            };

        }

        namespace totalMinutes {
            const prototype: {
            };

        }

        namespace totalSeconds {
            const prototype: {
            };

        }

    }

    export namespace clone {
        const prototype: {
        };

    }

    export namespace fromDates {
        const prototype: {
        };

    }

    export namespace fromDays {
        const prototype: {
        };

    }

    export namespace fromHours {
        const prototype: {
        };

    }

    export namespace fromMilliseconds {
        const prototype: {
        };

    }

    export namespace fromMinutes {
        const prototype: {
        };

    }

    export namespace fromSeconds {
        const prototype: {
        };

    }

    export namespace instanceOf {
        const prototype: {
        };

    }

    export namespace parse {
        const prototype: {
        };

    }

    export namespace parseDate {
        const prototype: {
        };

    }

    export namespace test {
        const prototype: {
        };

    }
}
